apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kubernetes-the-hard-way
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: trow.kube-public:31000
  environments:
  - key: dev
    owner: vivekcyber
    repository: jx3-kubernetes
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: true
      production: false
  pipelineUser:
    username: vivekcyber
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
