# Source: kuberhealthy/templates/khcheck-daemonset.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daemonset-khcheck
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
