# Source: kuberhealthy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuberhealthy
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: kuberhealthy
  namespace: jx
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: kuberhealthy
