# Source: jx-kh-check/templates/jx-pod-status-check.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-pod-status-sa
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
